version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: alejo
      POSTGRES_PASSWORD: alejo
      POSTGRES_DB: reto
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    environment:
      ENV: local
      DATABASE_URL: postgres://alejo:alejo@db:5432/reto
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: