database:
  user: alejo
  password: pScq43EKVh0zw2lhbDUripR259ysIWZI
  host: dpg-cu3sa23tq21c73ar0p7g-a.oregon-postgres.render.com
  name: retobd_w7s5
  port: 5432

security:
  secret_key: "aP3!x9@Q#z$2wE1^tY7&uI8*oL0%rF4+vB5~mN6"

rutas:
  accounts:
    get_all: "/accounts/get_all"
    get_by_id: "/accounts/get_by_id"
    create: "/accounts/massive"
  inventory: 
    get_all: "/inventories"
    get_by_id: "/inventories/get_by_id"
    create: "/inventories/massive"
  items:
    get_by_inventory: "/items/get_by_inventory"
    create: "/items/massive"
    delete: "/items/delete"