database:
  user: alejo
  password: alejo
  host: localhost
  name: reto
  port: 5432

security:
  secret_key: "=+&O]Oqb;aAg750H-JUzeG+-9&Tu~!gO"

rutas:
  accounts:
    get_all: "/accounts/get_all"
    get_by_id: "/accounts/get_by_id"
    create: "/accounts/massive"
  inventory: 
    get_all: "/inventories"
    get_by_id: "/inventories/get_by_id"
    create: "/inventories/massive"
  items:
    get_by_inventory: "/items/get_by_inventory"
    create: "/items/massive"